import { createContext, createElement, useContext, useEffect, useMemo, useState } from "react";

const languageStorageKey = "cleanflow-language";
const TranslationContext = createContext(null);

export const languageOptions = [
  { code: "en", label: "English" },
  { code: "pt", label: "Português" },
  { code: "es", label: "Español" },
];

const messages = {
  en: {
    "brand.operationsPlatform": "Operations platform", "brand.foundationBuild": "Foundation build",
    "navigation.dashboard": "Dashboard", "navigation.properties": "Properties", "navigation.jobs": "Jobs", "navigation.cleaners": "Cleaners", "navigation.payouts": "Payouts", "navigation.clients": "Clients", "navigation.devCenter": "Dev Center",
    "common.language": "Language", "common.mainNavigation": "Main navigation", "common.back": "Back", "common.cancel": "Cancel", "common.notProvided": "Not provided", "common.property": "Property", "common.client": "Client", "common.cleaner": "Cleaner", "common.status": "Status", "common.notes": "Notes", "common.active": "Active", "common.inactive": "Inactive", "common.date": "Date", "common.error": "Error",
    "language.english": "English", "language.portuguese": "Português", "language.spanish": "Español",
    "theme.switchToDark": "Switch to dark mode", "theme.switchToLight": "Switch to light mode",
    "notifications.checking": "Checking notifications…", "notifications.unavailable": "Notifications unavailable", "notifications.denied": "Notifications blocked", "notifications.enable": "Enable notifications", "notifications.enabling": "Enabling…", "notifications.enabled": "Notifications enabled", "notifications.error": "Unable to enable notifications. Try again.",
    "feedback.action": "Feedback", "feedback.title": "Send feedback", "feedback.intro": "Help us improve CleanFlow.", "feedback.type": "Feedback type", "feedback.typeSuggestion": "Suggestion", "feedback.typeBug": "Problem / Bug", "feedback.typeOther": "Other", "feedback.message": "Message", "feedback.messagePlaceholder": "Tell us what happened or what would help.", "feedback.submit": "Send feedback", "feedback.submitting": "Sending…", "feedback.successTitle": "Feedback sent", "feedback.successMessage": "Thank you. Your feedback was sent.", "feedback.failure": "Unable to send feedback. Please try again.", "feedback.messageRequired": "Enter a message.", "feedback.messageTooLong": "Keep your message under {count} characters.", "feedback.close": "Close",
    "pwa.updateAvailable": "New version available", "pwa.updateNow": "Update now",
    "devCenter.developmentOnly": "Developer only", "devCenter.title": "Dev Center", "devCenter.intro": "Generate isolated demo data for product testing.", "devCenter.environmentProduction": "Production target", "devCenter.environmentEmulator": "Emulator target", "devCenter.demoJobCount": "Demo jobs", "devCenter.quick": "Quick Demo", "devCenter.quickDescription": "10 jobs across today and the next 48 hours.", "devCenter.busyWeek": "Busy Week", "devCenter.busyWeekDescription": "35 jobs across the next seven days.", "devCenter.payoutTest": "Payout Test", "devCenter.payoutTestDescription": "5 completed unpaid jobs ready for payout testing.", "devCenter.managerTraining": "🎓 Manager Training", "devCenter.managerTrainingDescription": "A realistic operating week for learning and simulating workflows.", "devCenter.generate": "Generate", "devCenter.working": "Working…", "devCenter.clearTitle": "Clear demo data", "devCenter.clearDescription": "Deletes only records created by Dev Center.", "devCenter.clearConfirmation": "Clear all Dev Center demo data? This cannot be undone.", "devCenter.clearAction": "Clear demo data", "devCenter.generated": "Generated {count} demo jobs.", "devCenter.cleared": "Cleared {count} demo records.", "devCenter.error": "Dev Center could not complete that action.",
    "releases.action": "What's new", "releases.title": "What's new", "releases.intro": "See the latest improvements in CleanFlow.", "releases.currentVersion": "Current version {version}", "releases.unseen": "New updates available", "releases.close": "Close",
    "auth.loading": "Checking sign-in…", "auth.managerAccess": "Manager access", "auth.signIn": "Sign in", "auth.signingIn": "Signing in…", "auth.signInError": "Unable to sign in.", "auth.credentialsRequired": "Enter your email and password.", "auth.email": "Email", "auth.password": "Password", "auth.signOut": "Sign out", "auth.signingOut": "Signing out…", "auth.signOutError": "Unable to sign out.",
    "status.unassigned": "Unassigned", "status.offered": "Offered", "status.assigned": "Assigned", "status.inProgress": "In progress", "status.completed": "Completed", "status.pending": "Pending", "status.interested": "Interested", "status.declined": "Not available", "status.open": "Open", "status.resolved": "Resolved",
    "issueCategory.access": "Access", "issueCategory.supplies": "Supplies", "issueCategory.brokenItem": "Broken item", "issueCategory.heavyCleaning": "Heavy cleaning", "issueCategory.other": "Other",
    "dashboard.title": "Operations dashboard", "dashboard.subtitle": "Today's cleaning operation at a glance.", "dashboard.refresh": "Refresh dashboard", "dashboard.loading": "Loading dashboard…", "dashboard.error": "Unable to load dashboard.", "dashboard.needsAttention": "Needs attention", "dashboard.needsAttentionDescription": "Top operational priorities across assignments, cleaner interest, and issues.", "dashboard.recentlyCompleted": "Recently completed", "dashboard.activeOperation": "Active operation", "dashboard.needsAssignment": "Needs assignment", "dashboard.inProgress": "In progress", "dashboard.completed": "Completed", "dashboard.completedToday": "Completed today", "dashboard.jobsWithOpenIssues": "Jobs with open issues", "dashboard.managerWorkspace": "Manager workspace", "dashboard.totalJobs": "Total jobs", "dashboard.openIssues": "Open issues", "dashboard.priorities": "Priorities", "dashboard.noAttention": "No items need attention right now.", "dashboard.history": "History", "dashboard.noCompleted": "No completed jobs yet.", "dashboard.completionUnavailable": "Completion time unavailable", "dashboard.schedule": "Schedule", "dashboard.operation": "Operation", "dashboard.showActiveJobs": "Show active jobs", "dashboard.noMatchingJobs": "No jobs match this filter.", "dashboard.notAssigned": "Not assigned", "dashboard.openIssue": "Open issue", "dashboard.cleanerInterested": "Cleaner interested", "dashboard.cleanerInterestedDescription": "A cleaner is interested.", "dashboard.offersAwaitingResponse": "Offers awaiting response", "dashboard.noOffers": "No offers have been sent.", "dashboard.noInterestedCleaners": "No cleaner has expressed interest yet.", "dashboard.reviewIssue": "Review issue", "dashboard.reviewAndAssign": "Review & assign", "dashboard.sendOffers": "Send offers", "dashboard.reviewOffers": "Review offers", "dashboard.viewAll": "View all", "dashboard.next48Hours": "Next 48 hours", "dashboard.noNext48Hours": "No jobs scheduled in the next 48 hours.", "dashboard.thisWeek": "This week", "dashboard.weeklyScheduled": "Scheduled services", "dashboard.weeklyAssigned": "Assigned", "dashboard.weeklyNeedsAssignment": "Need assignment", "dashboard.weeklyCompleted": "Completed this week", "dashboard.dailyLoad": "Daily workload", "dashboard.today": "Today", "dashboard.tomorrow": "Tomorrow", "dashboard.followingDay": "Following day",
    "properties.title": "Properties", "properties.new": "New property", "properties.createTitle": "New property", "properties.name": "Property or address name", "properties.selectClient": "Select a client", "properties.linkClient": "Link client", "properties.currentClient": "Current client", "properties.loadingClients": "Loading clients…", "properties.clientsError": "Unable to load clients.", "properties.noActiveClients": "No active clients available.", "properties.confirmClientLink": "Confirm link", "properties.linkingClient": "Linking…", "properties.linkClientError": "Unable to link client.", "properties.save": "Save property", "properties.creating": "Saving…", "properties.nameRequired": "Enter a property name.", "properties.clientRequired": "Select a client.", "properties.priceInvalid": "Enter a valid non-negative price.", "properties.createError": "Unable to create property.", "properties.loading": "Loading properties…", "properties.error": "Unable to load properties.", "properties.empty": "No properties found.", "properties.unnamed": "Unnamed property", "properties.view": "View {property}", "properties.details": "Property details", "properties.defaultClientPrice": "Default client price", "properties.defaultCleanerPrice": "Default cleaner payout", "properties.createCleaning": "Create cleaning", "properties.upcomingService": "Upcoming service", "properties.noUpcomingService": "No upcoming service", "properties.cleaningHistory": "Cleaning history", "properties.historyLoading": "Loading property history…", "properties.historyError": "Unable to load property history.", "properties.noCleaningHistory": "No cleaning history yet.",
    "jobs.title": "Cleaning jobs", "jobs.loading": "Loading jobs…", "jobs.error": "Unable to load jobs.", "jobs.empty": "No jobs found.", "jobs.filterToday": "Scheduled today", "jobs.filterNeedsAssignment": "Needs assignment", "jobs.filterInProgress": "In progress", "jobs.filterCompletedToday": "Completed today", "jobs.details": "Job details", "jobs.new": "New job", "jobs.scheduledDate": "Scheduled date", "jobs.operationalStatus": "Operational status", "jobs.clientPrice": "Client price", "jobs.cleanerPayout": "Cleaner payout", "jobs.assignedCleaner": "Assigned cleaner", "jobs.assignedTime": "Assigned time", "jobs.startedTime": "Started time", "jobs.completedTime": "Completed time", "jobs.createdTime": "Created", "jobs.executionInProgress": "Cleaning in progress", "jobs.executionCompleted": "Cleaning completed", "jobs.startCleaning": "Start cleaning", "jobs.startingCleaning": "Starting…", "jobs.startCleaningError": "Unable to start cleaning.", "jobs.completeCleaning": "Complete cleaning", "jobs.completingCleaning": "Completing…", "jobs.completeCleaningError": "Unable to complete cleaning.", "jobs.create": "Create cleaning", "jobs.creating": "Creating…", "jobs.createError": "Unable to create cleaning.", "jobs.created": "Cleaning created", "jobs.saved": "Job saved", "jobs.viewJob": "View job", "jobs.backToProperties": "Back to properties", "jobs.backToJob": "Back to job", "jobs.backToJobs": "Back to jobs",
    "jobs.filters": "Job filters", "jobs.quickFilters": "Quick filters", "jobs.advancedFilters": "Filters", "jobs.advancedFiltersCount": "Filters ({count})", "jobs.quickToday": "Today", "jobs.search": "Search", "jobs.searchPlaceholder": "Search property or address", "jobs.statusFilter": "Status", "jobs.dateFilter": "Date", "jobs.cleanerFilter": "Cleaner", "jobs.propertyFilter": "Property", "jobs.filterAll": "All", "jobs.filterOffered": "Offered", "jobs.filterAssigned": "Assigned", "jobs.filterCompleted": "Completed", "jobs.dateAny": "Any date", "jobs.dateToday": "Today", "jobs.dateNext7Days": "Next 7 days", "jobs.datePast7Days": "Past 7 days", "jobs.datePast30Days": "Past 30 days", "jobs.anyCleaner": "Any cleaner", "jobs.anyProperty": "Any property", "jobs.clearFilters": "Clear filters", "jobs.results": "{count} services", "jobs.noMatchingFilters": "No jobs match these filters.",
    "jobs.loadMore": "Load more", "jobs.loadingMore": "Loading more…",
    "payouts.title": "Cleaner payouts", "payouts.refresh": "Refresh", "payouts.loading": "Loading payouts…", "payouts.error": "Unable to load payouts.", "payouts.empty": "No completed cleaner payouts are waiting.", "payouts.unpaidJobs": "Unpaid jobs: {count}", "payouts.total": "Total owed", "payouts.review": "Review", "payouts.backToPayouts": "Back to payouts", "payouts.paymentMethod": "Payment method", "payouts.selectPaymentMethod": "Select a payment method", "payouts.note": "Note (optional)", "payouts.markPaid": "Mark paid", "payouts.recording": "Recording…", "payouts.jobsRequired": "Select at least one job.", "payouts.paymentMethodRequired": "Select a payment method.", "payouts.jobNoLongerPayable": "One or more jobs are no longer payable. Refresh and review again.", "payouts.recordError": "Unable to record this payout.", "payouts.recorded": "Recorded {amount} for {count} jobs.",
    "payouts.proof": "Payment proof (optional)", "payouts.proofHelper": "Use a cropped payment confirmation when possible. Do not include balances or unrelated transactions.", "payouts.proofSelected": "Selected: {fileName}", "payouts.proofAttached": "Proof attached", "payouts.takePhoto": "Take photo", "payouts.chooseImage": "Choose image", "payouts.attachProof": "Attach proof", "payouts.retryProof": "Retry proof upload", "payouts.viewProof": "View proof", "payouts.uploadingProof": "Uploading proof… {percent}%", "payouts.proofRequired": "Choose an image proof to retry.", "payouts.proofInvalidType": "Choose a JPEG, PNG, WebP, HEIC, or HEIF image.", "payouts.proofTooLarge": "Choose an image no larger than 10 MB.", "payouts.proofUploadError": "Unable to upload the proof.", "payouts.proofViewError": "Unable to open the proof.", "payouts.proofRetryMessage": "The payout was recorded, but its proof was not uploaded. You can retry now or attach it later from payout history.", "payouts.recentHistory": "Recent payouts", "payouts.historyJobs": "Jobs: {count}",
    "offers.title": "Offers", "offers.offerToCleaners": "Offer to cleaners", "offers.loadingCleaners": "Loading cleaners…", "offers.cleanerError": "Unable to load cleaners.", "offers.emptyCleaners": "No active cleaners found.", "offers.send": "Send offers", "offers.sending": "Sending offers…", "offers.sendError": "Unable to send offers.", "offers.sent": "Offers sent", "offers.receivedOne": "{count} cleaner received an offer.", "offers.receivedMany": "{count} cleaners received offers.", "offers.loading": "Loading offers…", "offers.error": "Unable to load offers.", "offers.empty": "No offers sent yet.", "offers.refresh": "Refresh offers", "offers.responded": "Responded", "offers.simulateOffer": "Simulate offer", "offers.createPublicLink": "Create public link", "offers.creatingPublicLink": "Creating link…", "offers.openPublicLink": "Open public cleaner offer", "offers.publicLinkError": "Unable to create a public offer link.", "offers.assign": "Assign", "offers.assigning": "Assigning…", "offers.assignmentError": "Unable to assign cleaner.", "offers.alreadyAssigned": "This job is already assigned.", "offers.simulateAssignedCleaner": "Simulate assigned cleaner",
    "issues.title": "Issues", "issues.loading": "Loading issues…", "issues.error": "Unable to load issues.", "issues.empty": "No issues reported.", "issues.refresh": "Refresh issues", "issues.reportedBy": "Reported by {cleaner}", "issues.reported": "Reported", "issues.resolved": "Resolved", "issues.resolution": "Resolution", "issues.resolutionNote": "Resolution note (optional)", "issues.resolve": "Resolve issue", "issues.resolving": "Resolving…", "issues.resolveError": "Unable to resolve issue.", "issues.alreadyResolved": "This issue is already resolved.",
    "cleaner.developmentSimulation": "Development simulation", "cleaner.offerTitle": "Cleaning offer", "cleaner.assignedTitle": "Assigned cleaning", "cleaner.inProgressTitle": "Cleaning in progress", "cleaner.completedTitle": "Cleaning completed", "cleaner.offerStatus": "Offer status", "cleaner.interested": "I'm interested", "cleaner.notAvailable": "Not available", "cleaner.responseError": "Unable to save your response.", "cleaner.start": "Start cleaning", "cleaner.starting": "Starting…", "cleaner.startError": "Unable to start cleaning.", "cleaner.reportIssue": "Report issue", "cleaner.complete": "Complete cleaning", "cleaner.completeConfirmation": "Complete this cleaning?", "cleaner.completing": "Completing…", "cleaner.completeError": "Unable to complete cleaning.", "cleaner.issueTitle": "Cleaning issue", "cleaner.issueCategory": "Category", "cleaner.issueDescription": "Description", "cleaner.reportedBy": "Reported by", "cleaner.submitIssue": "Submit issue", "cleaner.reporting": "Reporting…", "cleaner.issueError": "Unable to report issue.", "cleaner.issueReported": "Issue reported", "cleaner.backToCleaning": "Back to cleaning",
    "publicOffer.eyebrow": "Cleaner offer", "publicOffer.title": "Cleaning opportunity", "publicOffer.loading": "Loading offer…", "publicOffer.notFound": "This offer link is not available.", "publicOffer.expired": "This offer link has expired.", "publicOffer.unavailable": "This offer is no longer available.", "publicOffer.loadError": "Unable to load this offer.", "publicOffer.serviceDate": "Service date", "publicOffer.startTime": "Start time", "publicOffer.yourPayment": "Your payment", "publicOffer.status": "Offer status", "publicOffer.responding": "Saving…", "publicOffer.responseError": "Unable to save your response.", "publicOffer.interestedConfirmation": "You expressed interest. The manager will confirm the assignment.", "publicOffer.declinedConfirmation": "You let the manager know you are not available.",
    "cleaners.title": "Cleaners", "cleaners.new": "New cleaner", "cleaners.loading": "Loading cleaners…", "cleaners.error": "Unable to load cleaners.", "cleaners.empty": "No cleaners found.", "cleaners.edit": "Edit {cleaner}", "cleaners.view": "View {cleaner}", "cleaners.details": "Cleaner details", "cleaners.upcomingServices": "Upcoming services", "cleaners.recentHistory": "Recent history", "cleaners.historyLoading": "Loading cleaner history…", "cleaners.historyError": "Unable to load cleaner history.", "cleaners.noUpcomingServices": "No upcoming services.", "cleaners.noRecentHistory": "No recent service history.", "cleaners.noPhone": "Phone not provided", "cleaners.createTitle": "New cleaner", "cleaners.editTitle": "Edit cleaner", "cleaners.name": "Name", "cleaners.phone": "Phone", "cleaners.phoneExample": "Example: +1 949 555 1234", "cleaners.preferredLanguage": "Preferred language", "cleaners.operations": "Operations", "cleaners.cityOrRegion": "City / region", "cleaners.teamType": "Team type", "cleaners.teamTypeSolo": "Solo", "cleaners.teamTypeCouple": "Couple", "cleaners.teamTypeTeam": "Team", "cleaners.teamTypeInvalid": "Choose a valid team type.", "cleaners.payment": "Payment", "cleaners.preferredPaymentMethod": "Preferred payment method", "cleaners.paymentContact": "Payment contact", "cleaners.paymentMethodCash": "Cash", "cleaners.paymentMethodCheck": "Check", "cleaners.paymentMethodOther": "Other", "cleaners.preferredPaymentMethodInvalid": "Choose a valid payment method.", "cleaners.internalNotes": "Internal notes", "cleaners.cityOrRegionTooLong": "Keep the city or region under {count} characters.", "cleaners.internalNotesTooLong": "Keep internal notes under {count} characters.", "cleaners.paymentContactTooLong": "Keep the payment contact under {count} characters.", "cleaners.save": "Save", "cleaners.saving": "Saving…", "cleaners.nameRequired": "Enter a cleaner name.", "cleaners.phoneRequired": "Enter a phone number before saving.", "cleaners.phoneInvalid": "Use an international phone number starting with +.", "cleaners.preferredLanguageRequired": "Choose a preferred language.", "cleaners.createError": "Unable to create cleaner.", "cleaners.updateError": "Unable to update cleaner.", "cleaners.created": "Cleaner created", "cleaners.updated": "Cleaner updated", "cleaners.backToDirectory": "Back to cleaners", "cleaners.backToDetail": "Back to cleaner",
    "clients.title": "Clients", "clients.new": "New client", "clients.loading": "Loading clients…", "clients.error": "Unable to load clients.", "clients.empty": "No clients found.", "clients.createTitle": "New client", "clients.name": "Client name", "clients.save": "Save client", "clients.creating": "Saving…", "clients.nameRequired": "Enter a client name.", "clients.createError": "Unable to create client.", "clients.view": "View {client}", "clients.details": "Client details", "clients.linkedProperties": "Linked properties", "clients.propertiesLoading": "Loading linked properties…", "clients.propertiesError": "Unable to load linked properties.", "clients.noLinkedProperties": "No linked properties.", "clients.openProperty": "Open property", "clients.upcomingService": "Upcoming service", "clients.noUpcomingService": "No upcoming service", "clients.recentHistory": "Recent history", "clients.historyLoading": "Loading client history…", "clients.historyError": "Unable to load client history.", "clients.noRecentHistory": "No recent service history.",
  },
  pt: {
    "brand.operationsPlatform": "Plataforma de operações", "brand.foundationBuild": "Versão inicial",
    "navigation.dashboard": "Painel", "navigation.properties": "Propriedades", "navigation.jobs": "Serviços", "navigation.cleaners": "Cleaners", "navigation.payouts": "Pagamentos", "navigation.clients": "Clientes", "navigation.devCenter": "Central Dev",
    "common.language": "Idioma", "common.mainNavigation": "Navegação principal", "common.back": "Voltar", "common.cancel": "Cancelar", "common.notProvided": "Não informado", "common.property": "Propriedade", "common.client": "Cliente", "common.cleaner": "Cleaner", "common.status": "Status", "common.notes": "Observações", "common.active": "Ativa", "common.inactive": "Inativa", "common.date": "Data", "common.error": "Erro",
    "language.english": "English", "language.portuguese": "Português", "language.spanish": "Español",
    "theme.switchToDark": "Ativar modo escuro", "theme.switchToLight": "Ativar modo claro",
    "notifications.checking": "Verificando notificações…", "notifications.unavailable": "Notificações indisponíveis", "notifications.denied": "Notificações bloqueadas", "notifications.enable": "Ativar notificações", "notifications.enabling": "Ativando…", "notifications.enabled": "Notificações ativadas", "notifications.error": "Não foi possível ativar as notificações. Tente novamente.",
    "feedback.action": "Feedback", "feedback.title": "Enviar feedback", "feedback.intro": "Ajude a melhorar o CleanFlow.", "feedback.type": "Tipo de feedback", "feedback.typeSuggestion": "Sugestão", "feedback.typeBug": "Problema / Bug", "feedback.typeOther": "Outro", "feedback.message": "Mensagem", "feedback.messagePlaceholder": "Conte o que aconteceu ou o que ajudaria.", "feedback.submit": "Enviar feedback", "feedback.submitting": "Enviando…", "feedback.successTitle": "Feedback enviado", "feedback.successMessage": "Agradecemos. Seu feedback foi enviado.", "feedback.failure": "Não foi possível enviar o feedback. Tente novamente.", "feedback.messageRequired": "Digite uma mensagem.", "feedback.messageTooLong": "Use no máximo {count} caracteres.", "feedback.close": "Fechar",
    "pwa.updateAvailable": "Nova versão disponível", "pwa.updateNow": "Atualizar agora",
    "devCenter.developmentOnly": "Somente desenvolvimento", "devCenter.title": "Central Dev", "devCenter.intro": "Gere dados de demonstração isolados para testes de produto.", "devCenter.environmentProduction": "Ambiente de produção", "devCenter.environmentEmulator": "Ambiente de emulador", "devCenter.demoJobCount": "Serviços de demonstração", "devCenter.quick": "Demo rápida", "devCenter.quickDescription": "10 serviços entre hoje e as próximas 48 horas.", "devCenter.busyWeek": "Semana cheia", "devCenter.busyWeekDescription": "35 serviços nos próximos sete dias.", "devCenter.payoutTest": "Teste de pagamento", "devCenter.payoutTestDescription": "5 serviços concluídos e não pagos para testar pagamentos.", "devCenter.managerTraining": "🎓 Treinamento da gerente", "devCenter.managerTrainingDescription": "Uma semana realista de operação para aprender e simular fluxos.", "devCenter.generate": "Gerar", "devCenter.working": "Processando…", "devCenter.clearTitle": "Limpar dados de demonstração", "devCenter.clearDescription": "Exclui somente registros criados pela Central Dev.", "devCenter.clearConfirmation": "Limpar todos os dados de demonstração da Central Dev? Esta ação não pode ser desfeita.", "devCenter.clearAction": "Limpar dados de demonstração", "devCenter.generated": "{count} serviços de demonstração gerados.", "devCenter.cleared": "{count} registros de demonstração removidos.", "devCenter.error": "A Central Dev não conseguiu concluir esta ação.",
    "releases.action": "Novidades", "releases.title": "Novidades", "releases.intro": "Veja as últimas melhorias no CleanFlow.", "releases.currentVersion": "Versão atual {version}", "releases.unseen": "Novidades disponíveis", "releases.close": "Fechar",
    "auth.loading": "Verificando acesso…", "auth.managerAccess": "Acesso da gerente", "auth.signIn": "Entrar", "auth.signingIn": "Entrando…", "auth.signInError": "Não foi possível entrar.", "auth.credentialsRequired": "Informe seu e-mail e senha.", "auth.email": "E-mail", "auth.password": "Senha", "auth.signOut": "Sair", "auth.signingOut": "Saindo…", "auth.signOutError": "Não foi possível sair.",
    "status.unassigned": "Não atribuída", "status.offered": "Oferecida", "status.assigned": "Atribuída", "status.inProgress": "Em andamento", "status.completed": "Concluída", "status.pending": "Pendente", "status.interested": "Interessada", "status.declined": "Não disponível", "status.open": "Aberto", "status.resolved": "Resolvido",
    "issueCategory.access": "Acesso", "issueCategory.supplies": "Suprimentos", "issueCategory.brokenItem": "Item quebrado", "issueCategory.heavyCleaning": "Limpeza pesada", "issueCategory.other": "Outro",
    "dashboard.title": "Painel de operações", "dashboard.subtitle": "Visão geral das operações de limpeza de hoje.", "dashboard.refresh": "Atualizar painel", "dashboard.loading": "Carregando painel…", "dashboard.error": "Não foi possível carregar o painel.", "dashboard.needsAttention": "Precisa de atenção", "dashboard.recentlyCompleted": "Concluídos recentemente", "dashboard.activeOperation": "Operação em andamento", "dashboard.needsAssignment": "Precisa de atribuição", "dashboard.inProgress": "Em andamento", "dashboard.completed": "Concluídos", "dashboard.completedToday": "Concluídos hoje", "dashboard.jobsWithOpenIssues": "Serviços com problemas em aberto", "dashboard.managerWorkspace": "Área da gerente", "dashboard.totalJobs": "Total de serviços", "dashboard.openIssues": "Problemas em aberto", "dashboard.priorities": "Prioridades", "dashboard.noAttention": "Nenhum item precisa de atenção agora.", "dashboard.history": "Histórico", "dashboard.noCompleted": "Ainda não há serviços concluídos.", "dashboard.completionUnavailable": "Horário de conclusão não disponível", "dashboard.schedule": "Agenda", "dashboard.operation": "Operação", "dashboard.showActiveJobs": "Mostrar serviços ativos", "dashboard.noMatchingJobs": "Nenhum serviço corresponde a este filtro.", "dashboard.notAssigned": "Não atribuída", "dashboard.openIssue": "Problema em aberto", "dashboard.cleanerInterested": "Cleaner interessada", "dashboard.cleanerInterestedDescription": "Uma cleaner demonstrou interesse.", "dashboard.offersAwaitingResponse": "Ofertas aguardando resposta", "dashboard.noOffers": "Nenhuma oferta foi enviada.", "dashboard.noInterestedCleaners": "Nenhuma cleaner demonstrou interesse ainda.", "dashboard.reviewIssue": "Revisar problema", "dashboard.reviewAndAssign": "Revisar e atribuir", "dashboard.sendOffers": "Enviar ofertas", "dashboard.reviewOffers": "Revisar ofertas", "dashboard.viewAll": "Ver todos", "dashboard.next48Hours": "Próximas 48 horas", "dashboard.noNext48Hours": "Nenhum serviço agendado nas próximas 48 horas.", "dashboard.thisWeek": "Esta semana", "dashboard.weeklyScheduled": "Serviços agendados", "dashboard.weeklyAssigned": "Atribuídos", "dashboard.weeklyNeedsAssignment": "Precisam de atribuição", "dashboard.weeklyCompleted": "Concluídos nesta semana", "dashboard.dailyLoad": "Carga diária", "dashboard.today": "Hoje", "dashboard.tomorrow": "Amanhã", "dashboard.followingDay": "Dia seguinte",
    "properties.title": "Propriedades", "properties.new": "Nova propriedade", "properties.createTitle": "Nova propriedade", "properties.name": "Nome ou endereço da propriedade", "properties.selectClient": "Selecione um cliente", "properties.linkClient": "Vincular cliente", "properties.currentClient": "Cliente atual", "properties.loadingClients": "Carregando clientes…", "properties.clientsError": "Não foi possível carregar os clientes.", "properties.noActiveClients": "Nenhum cliente ativo disponível.", "properties.confirmClientLink": "Confirmar vínculo", "properties.linkingClient": "Vinculando…", "properties.linkClientError": "Não foi possível vincular o cliente.", "properties.save": "Salvar propriedade", "properties.creating": "Salvando…", "properties.nameRequired": "Informe o nome da propriedade.", "properties.clientRequired": "Selecione um cliente.", "properties.priceInvalid": "Informe um preço válido, igual ou maior que zero.", "properties.createError": "Não foi possível criar a propriedade.", "properties.loading": "Carregando propriedades…", "properties.error": "Não foi possível carregar as propriedades.", "properties.empty": "Nenhuma propriedade encontrada.", "properties.unnamed": "Propriedade sem nome", "properties.view": "Ver {property}", "properties.details": "Detalhes da propriedade", "properties.defaultClientPrice": "Preço padrão para o cliente", "properties.defaultCleanerPrice": "Pagamento padrão da cleaner", "properties.createCleaning": "Criar limpeza", "properties.upcomingService": "Próximo serviço", "properties.noUpcomingService": "Nenhum serviço futuro", "properties.cleaningHistory": "Histórico de limpezas", "properties.historyLoading": "Carregando histórico da propriedade…", "properties.historyError": "Não foi possível carregar o histórico da propriedade.", "properties.noCleaningHistory": "Ainda não há histórico de limpezas.",
    "jobs.title": "Serviços de limpeza", "jobs.loading": "Carregando serviços…", "jobs.error": "Não foi possível carregar os serviços.", "jobs.empty": "Nenhum serviço encontrado.", "jobs.filterToday": "Agendados para hoje", "jobs.filterNeedsAssignment": "Precisa de atribuição", "jobs.filterInProgress": "Em andamento", "jobs.filterCompletedToday": "Concluídos hoje", "jobs.details": "Detalhes do serviço", "jobs.new": "Novo serviço", "jobs.scheduledDate": "Data agendada", "jobs.operationalStatus": "Status operacional", "jobs.clientPrice": "Preço para o cliente", "jobs.cleanerPayout": "Pagamento da cleaner", "jobs.assignedCleaner": "Cleaner responsável", "jobs.assignedTime": "Horário da atribuição", "jobs.startedTime": "Horário de início", "jobs.completedTime": "Horário de conclusão", "jobs.createdTime": "Criado em", "jobs.executionInProgress": "Limpeza em andamento", "jobs.executionCompleted": "Limpeza concluída", "jobs.startCleaning": "Iniciar limpeza", "jobs.startingCleaning": "Iniciando…", "jobs.startCleaningError": "Não foi possível iniciar a limpeza.", "jobs.completeCleaning": "Concluir limpeza", "jobs.completingCleaning": "Concluindo…", "jobs.completeCleaningError": "Não foi possível concluir a limpeza.", "jobs.create": "Criar limpeza", "jobs.creating": "Criando…", "jobs.createError": "Não foi possível criar a limpeza.", "jobs.created": "Limpeza criada", "jobs.saved": "Serviço salvo", "jobs.viewJob": "Ver serviço", "jobs.backToProperties": "Voltar para propriedades", "jobs.backToJob": "Voltar para o serviço", "jobs.backToJobs": "Voltar para serviços",
    "jobs.filters": "Filtros de serviços", "jobs.quickFilters": "Filtros rápidos", "jobs.advancedFilters": "Filtros", "jobs.advancedFiltersCount": "Filtros ({count})", "jobs.quickToday": "Hoje", "jobs.search": "Buscar", "jobs.searchPlaceholder": "Buscar propriedade ou endereço", "jobs.statusFilter": "Status", "jobs.dateFilter": "Data", "jobs.cleanerFilter": "Cleaner", "jobs.propertyFilter": "Propriedade", "jobs.filterAll": "Todos", "jobs.filterOffered": "Oferecidos", "jobs.filterAssigned": "Atribuídos", "jobs.filterCompleted": "Concluídos", "jobs.dateAny": "Qualquer data", "jobs.dateToday": "Hoje", "jobs.dateNext7Days": "Próximos 7 dias", "jobs.datePast7Days": "Últimos 7 dias", "jobs.datePast30Days": "Últimos 30 dias", "jobs.anyCleaner": "Qualquer cleaner", "jobs.anyProperty": "Qualquer propriedade", "jobs.clearFilters": "Limpar filtros", "jobs.results": "{count} serviços", "jobs.noMatchingFilters": "Nenhum serviço corresponde a estes filtros.",
    "jobs.loadMore": "Carregar mais", "jobs.loadingMore": "Carregando mais…",
    "payouts.title": "Pagamentos de cleaners", "payouts.refresh": "Atualizar", "payouts.loading": "Carregando pagamentos…", "payouts.error": "Não foi possível carregar os pagamentos.", "payouts.empty": "Não há pagamentos de cleaners pendentes.", "payouts.unpaidJobs": "Serviços não pagos: {count}", "payouts.total": "Total a pagar", "payouts.review": "Revisar", "payouts.backToPayouts": "Voltar para pagamentos", "payouts.paymentMethod": "Método de pagamento", "payouts.selectPaymentMethod": "Selecione um método de pagamento", "payouts.note": "Observação (opcional)", "payouts.markPaid": "Marcar como pago", "payouts.recording": "Registrando…", "payouts.jobsRequired": "Selecione pelo menos um serviço.", "payouts.paymentMethodRequired": "Selecione um método de pagamento.", "payouts.jobNoLongerPayable": "Um ou mais serviços não estão mais disponíveis para pagamento. Atualize e revise novamente.", "payouts.recordError": "Não foi possível registrar este pagamento.", "payouts.recorded": "Pagamento de {amount} registrado para {count} serviços.",
    "payouts.proof": "Comprovante de pagamento (opcional)", "payouts.proofHelper": "Use uma confirmação de pagamento recortada quando possível. Não inclua saldos ou transações não relacionadas.", "payouts.proofSelected": "Selecionado: {fileName}", "payouts.proofAttached": "Comprovante anexado", "payouts.takePhoto": "Tirar foto", "payouts.chooseImage": "Escolher imagem", "payouts.attachProof": "Anexar comprovante", "payouts.retryProof": "Tentar enviar o comprovante novamente", "payouts.viewProof": "Ver comprovante", "payouts.uploadingProof": "Enviando comprovante… {percent}%", "payouts.proofRequired": "Escolha uma imagem de comprovante para tentar novamente.", "payouts.proofInvalidType": "Escolha uma imagem JPEG, PNG, WebP, HEIC ou HEIF.", "payouts.proofTooLarge": "Escolha uma imagem de no máximo 10 MB.", "payouts.proofUploadError": "Não foi possível enviar o comprovante.", "payouts.proofViewError": "Não foi possível abrir o comprovante.", "payouts.proofRetryMessage": "O pagamento foi registrado, mas o comprovante não foi enviado. Você pode tentar novamente agora ou anexá-lo depois no histórico de pagamentos.", "payouts.recentHistory": "Pagamentos recentes", "payouts.historyJobs": "Serviços: {count}",
    "offers.title": "Ofertas", "offers.offerToCleaners": "Oferecer para cleaners", "offers.loadingCleaners": "Carregando cleaners…", "offers.cleanerError": "Não foi possível carregar as cleaners.", "offers.emptyCleaners": "Nenhuma cleaner ativa encontrada.", "offers.send": "Enviar ofertas", "offers.sending": "Enviando ofertas…", "offers.sendError": "Não foi possível enviar as ofertas.", "offers.sent": "Ofertas enviadas", "offers.receivedOne": "{count} cleaner recebeu uma oferta.", "offers.receivedMany": "{count} cleaners receberam ofertas.", "offers.loading": "Carregando ofertas…", "offers.error": "Não foi possível carregar as ofertas.", "offers.empty": "Nenhuma oferta enviada ainda.", "offers.refresh": "Atualizar ofertas", "offers.responded": "Respondeu em", "offers.simulateOffer": "Simular oferta", "offers.createPublicLink": "Criar link público", "offers.creatingPublicLink": "Criando link…", "offers.openPublicLink": "Abrir oferta pública para cleaner", "offers.publicLinkError": "Não foi possível criar o link público da oferta.", "offers.assign": "Atribuir", "offers.assigning": "Atribuindo…", "offers.assignmentError": "Não foi possível atribuir a cleaner.", "offers.alreadyAssigned": "Este serviço já está atribuído.", "offers.simulateAssignedCleaner": "Simular cleaner responsável",
    "issues.title": "Problemas", "issues.loading": "Carregando problemas…", "issues.error": "Não foi possível carregar os problemas.", "issues.empty": "Nenhum problema relatado.", "issues.refresh": "Atualizar problemas", "issues.reportedBy": "Relatado por {cleaner}", "issues.reported": "Relatado em", "issues.resolved": "Resolvido em", "issues.resolution": "Resolução", "issues.resolutionNote": "Nota de resolução (opcional)", "issues.resolve": "Resolver problema", "issues.resolving": "Resolvendo…", "issues.resolveError": "Não foi possível resolver o problema.", "issues.alreadyResolved": "Este problema já foi resolvido.",
    "cleaner.developmentSimulation": "Simulação de desenvolvimento", "cleaner.offerTitle": "Oferta de limpeza", "cleaner.assignedTitle": "Limpeza atribuída", "cleaner.inProgressTitle": "Limpeza em andamento", "cleaner.completedTitle": "Limpeza concluída", "cleaner.offerStatus": "Status da oferta", "cleaner.interested": "Tenho interesse", "cleaner.notAvailable": "Não posso", "cleaner.responseError": "Não foi possível salvar sua resposta.", "cleaner.start": "Iniciar limpeza", "cleaner.starting": "Iniciando…", "cleaner.startError": "Não foi possível iniciar a limpeza.", "cleaner.reportIssue": "Informar problema", "cleaner.complete": "Concluir limpeza", "cleaner.completeConfirmation": "Concluir esta limpeza?", "cleaner.completing": "Concluindo…", "cleaner.completeError": "Não foi possível concluir a limpeza.", "cleaner.issueTitle": "Problema na limpeza", "cleaner.issueCategory": "Categoria", "cleaner.issueDescription": "Descrição", "cleaner.reportedBy": "Relatado por", "cleaner.submitIssue": "Enviar problema", "cleaner.reporting": "Enviando…", "cleaner.issueError": "Não foi possível informar o problema.", "cleaner.issueReported": "Problema informado", "cleaner.backToCleaning": "Voltar para a limpeza",
    "publicOffer.eyebrow": "Oferta para cleaner", "publicOffer.title": "Oportunidade de limpeza", "publicOffer.loading": "Carregando oferta…", "publicOffer.notFound": "Este link de oferta não está disponível.", "publicOffer.expired": "Este link de oferta expirou.", "publicOffer.unavailable": "Esta oferta não está mais disponível.", "publicOffer.loadError": "Não foi possível carregar esta oferta.", "publicOffer.serviceDate": "Data do serviço", "publicOffer.startTime": "Horário de início", "publicOffer.yourPayment": "Seu pagamento", "publicOffer.status": "Status da oferta", "publicOffer.responding": "Salvando…", "publicOffer.responseError": "Não foi possível salvar sua resposta.", "publicOffer.interestedConfirmation": "Você demonstrou interesse. A gerente confirmará a atribuição.", "publicOffer.declinedConfirmation": "Você avisou a gerente que não está disponível.",
    "cleaners.title": "Cleaners", "cleaners.new": "Nova cleaner", "cleaners.loading": "Carregando cleaners…", "cleaners.error": "Não foi possível carregar as cleaners.", "cleaners.empty": "Nenhuma cleaner encontrada.", "cleaners.edit": "Editar {cleaner}", "cleaners.view": "Ver {cleaner}", "cleaners.details": "Detalhes da cleaner", "cleaners.upcomingServices": "Próximos serviços", "cleaners.recentHistory": "Histórico recente", "cleaners.historyLoading": "Carregando histórico da cleaner…", "cleaners.historyError": "Não foi possível carregar o histórico da cleaner.", "cleaners.noUpcomingServices": "Nenhum próximo serviço.", "cleaners.noRecentHistory": "Nenhum histórico recente de serviços.", "cleaners.noPhone": "Telefone não informado", "cleaners.createTitle": "Nova cleaner", "cleaners.editTitle": "Editar cleaner", "cleaners.name": "Nome", "cleaners.phone": "Telefone", "cleaners.phoneExample": "Ex.: +1 949 555 1234", "cleaners.preferredLanguage": "Idioma preferido", "cleaners.operations": "Operações", "cleaners.cityOrRegion": "Cidade / região", "cleaners.teamType": "Tipo de equipe", "cleaners.teamTypeSolo": "Sozinha", "cleaners.teamTypeCouple": "Casal", "cleaners.teamTypeTeam": "Equipe", "cleaners.teamTypeInvalid": "Escolha um tipo de equipe válido.", "cleaners.payment": "Pagamento", "cleaners.preferredPaymentMethod": "Método de pagamento preferido", "cleaners.paymentContact": "Contato para pagamento", "cleaners.paymentMethodCash": "Dinheiro", "cleaners.paymentMethodCheck": "Cheque", "cleaners.paymentMethodOther": "Outro", "cleaners.preferredPaymentMethodInvalid": "Escolha um método de pagamento válido.", "cleaners.internalNotes": "Observações internas", "cleaners.cityOrRegionTooLong": "Use no máximo {count} caracteres para cidade ou região.", "cleaners.internalNotesTooLong": "Use no máximo {count} caracteres nas observações internas.", "cleaners.paymentContactTooLong": "Use no máximo {count} caracteres no contato para pagamento.", "cleaners.save": "Salvar", "cleaners.saving": "Salvando…", "cleaners.nameRequired": "Informe o nome da cleaner.", "cleaners.phoneRequired": "Informe um telefone antes de salvar.", "cleaners.phoneInvalid": "Use um telefone internacional começando com +.", "cleaners.preferredLanguageRequired": "Escolha um idioma preferido.", "cleaners.createError": "Não foi possível criar a cleaner.", "cleaners.updateError": "Não foi possível atualizar a cleaner.", "cleaners.created": "Cleaner criada", "cleaners.updated": "Cleaner atualizada", "cleaners.backToDirectory": "Voltar para cleaners", "cleaners.backToDetail": "Voltar para a cleaner",
    "clients.title": "Clientes", "clients.new": "Novo cliente", "clients.loading": "Carregando clientes…", "clients.error": "Não foi possível carregar os clientes.", "clients.empty": "Nenhum cliente encontrado.", "clients.createTitle": "Novo cliente", "clients.name": "Nome do cliente", "clients.save": "Salvar cliente", "clients.creating": "Salvando…", "clients.nameRequired": "Informe o nome do cliente.", "clients.createError": "Não foi possível criar o cliente.", "clients.view": "Ver {client}", "clients.details": "Detalhes do cliente", "clients.linkedProperties": "Propriedades vinculadas", "clients.propertiesLoading": "Carregando propriedades vinculadas…", "clients.propertiesError": "Não foi possível carregar as propriedades vinculadas.", "clients.noLinkedProperties": "Nenhuma propriedade vinculada.", "clients.openProperty": "Abrir propriedade", "clients.upcomingService": "Próximo serviço", "clients.noUpcomingService": "Nenhum próximo serviço", "clients.recentHistory": "Histórico recente", "clients.historyLoading": "Carregando histórico do cliente…", "clients.historyError": "Não foi possível carregar o histórico do cliente.", "clients.noRecentHistory": "Nenhum histórico recente de serviços.",
    "dashboard.needsAttentionDescription": "Principais prioridades operacionais entre atribuições, interesse de cleaners e problemas.",
  },
  es: {
    "brand.operationsPlatform": "Plataforma de operaciones", "brand.foundationBuild": "Versión inicial",
    "navigation.dashboard": "Panel", "navigation.properties": "Propiedades", "navigation.jobs": "Servicios", "navigation.cleaners": "Cleaners", "navigation.payouts": "Pagos", "navigation.clients": "Clientes", "navigation.devCenter": "Centro Dev",
    "common.language": "Idioma", "common.mainNavigation": "Navegación principal", "common.back": "Volver", "common.cancel": "Cancelar", "common.notProvided": "No indicado", "common.property": "Propiedad", "common.client": "Cliente", "common.cleaner": "Cleaner", "common.status": "Estado", "common.notes": "Notas", "common.active": "Activa", "common.inactive": "Inactiva", "common.date": "Fecha", "common.error": "Error",
    "language.english": "English", "language.portuguese": "Português", "language.spanish": "Español",
    "theme.switchToDark": "Activar modo oscuro", "theme.switchToLight": "Activar modo claro",
    "notifications.checking": "Comprobando notificaciones…", "notifications.unavailable": "Notificaciones no disponibles", "notifications.denied": "Notificaciones bloqueadas", "notifications.enable": "Activar notificaciones", "notifications.enabling": "Activando…", "notifications.enabled": "Notificaciones activadas", "notifications.error": "No se pudieron activar las notificaciones. Inténtalo de nuevo.",
    "feedback.action": "Comentarios", "feedback.title": "Enviar comentarios", "feedback.intro": "Ayúdanos a mejorar CleanFlow.", "feedback.type": "Tipo de comentario", "feedback.typeSuggestion": "Sugerencia", "feedback.typeBug": "Problema / Error", "feedback.typeOther": "Otro", "feedback.message": "Mensaje", "feedback.messagePlaceholder": "Cuéntanos qué ocurrió o qué sería útil.", "feedback.submit": "Enviar comentarios", "feedback.submitting": "Enviando…", "feedback.successTitle": "Comentarios enviados", "feedback.successMessage": "Gracias. Tus comentarios fueron enviados.", "feedback.failure": "No se pudieron enviar tus comentarios. Inténtalo de nuevo.", "feedback.messageRequired": "Escribe un mensaje.", "feedback.messageTooLong": "Usa como máximo {count} caracteres.", "feedback.close": "Cerrar",
    "pwa.updateAvailable": "Nueva versión disponible", "pwa.updateNow": "Actualizar ahora",
    "devCenter.developmentOnly": "Solo desarrollo", "devCenter.title": "Centro Dev", "devCenter.intro": "Genera datos de demostración aislados para pruebas de producto.", "devCenter.environmentProduction": "Entorno de producción", "devCenter.environmentEmulator": "Entorno de emulador", "devCenter.demoJobCount": "Servicios de demostración", "devCenter.quick": "Demo rápida", "devCenter.quickDescription": "10 servicios entre hoy y las próximas 48 horas.", "devCenter.busyWeek": "Semana intensa", "devCenter.busyWeekDescription": "35 servicios durante los próximos siete días.", "devCenter.payoutTest": "Prueba de pagos", "devCenter.payoutTestDescription": "5 servicios completados y sin pagar para probar pagos.", "devCenter.managerTraining": "🎓 Capacitación de la gerente", "devCenter.managerTrainingDescription": "Una semana operativa realista para aprender y simular flujos.", "devCenter.generate": "Generar", "devCenter.working": "Procesando…", "devCenter.clearTitle": "Limpiar datos de demostración", "devCenter.clearDescription": "Elimina solo los registros creados por Centro Dev.", "devCenter.clearConfirmation": "¿Limpiar todos los datos de demostración de Centro Dev? Esta acción no se puede deshacer.", "devCenter.clearAction": "Limpiar datos de demostración", "devCenter.generated": "Se generaron {count} servicios de demostración.", "devCenter.cleared": "Se eliminaron {count} registros de demostración.", "devCenter.error": "Centro Dev no pudo completar esta acción.",
    "releases.action": "Novedades", "releases.title": "Novedades", "releases.intro": "Conoce las últimas mejoras de CleanFlow.", "releases.currentVersion": "Versión actual {version}", "releases.unseen": "Hay novedades disponibles", "releases.close": "Cerrar",
    "auth.loading": "Verificando acceso…", "auth.managerAccess": "Acceso de gestión", "auth.signIn": "Ingresar", "auth.signingIn": "Ingresando…", "auth.signInError": "No se pudo iniciar sesión.", "auth.credentialsRequired": "Ingresa tu correo electrónico y contraseña.", "auth.email": "Correo electrónico", "auth.password": "Contraseña", "auth.signOut": "Cerrar sesión", "auth.signingOut": "Cerrando sesión…", "auth.signOutError": "No se pudo cerrar sesión.",
    "status.unassigned": "Sin asignar", "status.offered": "Ofrecida", "status.assigned": "Asignada", "status.inProgress": "En progreso", "status.completed": "Completada", "status.pending": "Pendiente", "status.interested": "Interesada", "status.declined": "No disponible", "status.open": "Abierto", "status.resolved": "Resuelto",
    "issueCategory.access": "Acceso", "issueCategory.supplies": "Suministros", "issueCategory.brokenItem": "Artículo dañado", "issueCategory.heavyCleaning": "Limpieza profunda", "issueCategory.other": "Otro",
    "dashboard.title": "Panel de operaciones", "dashboard.subtitle": "Resumen de las operaciones de limpieza de hoy.", "dashboard.refresh": "Actualizar panel", "dashboard.loading": "Cargando panel…", "dashboard.error": "No se pudo cargar el panel.", "dashboard.needsAttention": "Requiere atención", "dashboard.recentlyCompleted": "Completados recientemente", "dashboard.activeOperation": "Operación en curso", "dashboard.needsAssignment": "Requiere asignación", "dashboard.inProgress": "En progreso", "dashboard.completed": "Completados", "dashboard.completedToday": "Completados hoy", "dashboard.jobsWithOpenIssues": "Servicios con problemas abiertos", "dashboard.managerWorkspace": "Área de gestión", "dashboard.totalJobs": "Total de servicios", "dashboard.openIssues": "Problemas abiertos", "dashboard.priorities": "Prioridades", "dashboard.noAttention": "No hay elementos que requieran atención ahora.", "dashboard.history": "Historial", "dashboard.noCompleted": "Aún no hay servicios completados.", "dashboard.completionUnavailable": "Hora de finalización no disponible", "dashboard.schedule": "Calendario", "dashboard.operation": "Operación", "dashboard.showActiveJobs": "Mostrar servicios activos", "dashboard.noMatchingJobs": "Ningún servicio coincide con este filtro.", "dashboard.notAssigned": "Sin asignar", "dashboard.openIssue": "Problema abierto", "dashboard.cleanerInterested": "Cleaner interesada", "dashboard.cleanerInterestedDescription": "Una cleaner expresó interés.", "dashboard.offersAwaitingResponse": "Ofertas en espera de respuesta", "dashboard.noOffers": "No se han enviado ofertas.", "dashboard.noInterestedCleaners": "Ninguna cleaner ha expresado interés todavía.", "dashboard.reviewIssue": "Revisar problema", "dashboard.reviewAndAssign": "Revisar y asignar", "dashboard.sendOffers": "Enviar ofertas", "dashboard.reviewOffers": "Revisar ofertas", "dashboard.viewAll": "Ver todos", "dashboard.next48Hours": "Próximas 48 horas", "dashboard.noNext48Hours": "No hay servicios programados en las próximas 48 horas.", "dashboard.thisWeek": "Esta semana", "dashboard.weeklyScheduled": "Servicios programados", "dashboard.weeklyAssigned": "Asignados", "dashboard.weeklyNeedsAssignment": "Requieren asignación", "dashboard.weeklyCompleted": "Completados esta semana", "dashboard.dailyLoad": "Carga diaria", "dashboard.today": "Hoy", "dashboard.tomorrow": "Mañana", "dashboard.followingDay": "Día siguiente",
    "properties.title": "Propiedades", "properties.new": "Nueva propiedad", "properties.createTitle": "Nueva propiedad", "properties.name": "Nombre o dirección de la propiedad", "properties.selectClient": "Selecciona un cliente", "properties.linkClient": "Vincular cliente", "properties.currentClient": "Cliente actual", "properties.loadingClients": "Cargando clientes…", "properties.clientsError": "No se pudieron cargar los clientes.", "properties.noActiveClients": "No hay clientes activos disponibles.", "properties.confirmClientLink": "Confirmar vínculo", "properties.linkingClient": "Vinculando…", "properties.linkClientError": "No se pudo vincular el cliente.", "properties.save": "Guardar propiedad", "properties.creating": "Guardando…", "properties.nameRequired": "Ingresa el nombre de la propiedad.", "properties.clientRequired": "Selecciona un cliente.", "properties.priceInvalid": "Ingresa un precio válido que no sea negativo.", "properties.createError": "No se pudo crear la propiedad.", "properties.loading": "Cargando propiedades…", "properties.error": "No se pudieron cargar las propiedades.", "properties.empty": "No se encontraron propiedades.", "properties.unnamed": "Propiedad sin nombre", "properties.view": "Ver {property}", "properties.details": "Detalles de la propiedad", "properties.defaultClientPrice": "Precio predeterminado para el cliente", "properties.defaultCleanerPrice": "Pago predeterminado de la cleaner", "properties.createCleaning": "Crear limpieza", "properties.upcomingService": "Próximo servicio", "properties.noUpcomingService": "No hay próximos servicios", "properties.cleaningHistory": "Historial de limpiezas", "properties.historyLoading": "Cargando el historial de la propiedad…", "properties.historyError": "No se pudo cargar el historial de la propiedad.", "properties.noCleaningHistory": "Aún no hay historial de limpiezas.",
    "jobs.title": "Servicios de limpieza", "jobs.loading": "Cargando servicios…", "jobs.error": "No se pudieron cargar los servicios.", "jobs.empty": "No se encontraron servicios.", "jobs.filterToday": "Programados para hoy", "jobs.filterNeedsAssignment": "Requiere asignación", "jobs.filterInProgress": "En progreso", "jobs.filterCompletedToday": "Completados hoy", "jobs.details": "Detalles del servicio", "jobs.new": "Nuevo servicio", "jobs.scheduledDate": "Fecha programada", "jobs.operationalStatus": "Estado operativo", "jobs.clientPrice": "Precio para el cliente", "jobs.cleanerPayout": "Pago de la cleaner", "jobs.assignedCleaner": "Cleaner responsable", "jobs.assignedTime": "Hora de asignación", "jobs.startedTime": "Hora de inicio", "jobs.completedTime": "Hora de finalización", "jobs.createdTime": "Creado", "jobs.executionInProgress": "Limpieza en progreso", "jobs.executionCompleted": "Limpieza completada", "jobs.startCleaning": "Iniciar limpieza", "jobs.startingCleaning": "Iniciando…", "jobs.startCleaningError": "No se pudo iniciar la limpieza.", "jobs.completeCleaning": "Completar limpieza", "jobs.completingCleaning": "Completando…", "jobs.completeCleaningError": "No se pudo completar la limpieza.", "jobs.create": "Crear limpieza", "jobs.creating": "Creando…", "jobs.createError": "No se pudo crear la limpieza.", "jobs.created": "Limpieza creada", "jobs.saved": "Servicio guardado", "jobs.viewJob": "Ver servicio", "jobs.backToProperties": "Volver a propiedades", "jobs.backToJob": "Volver al servicio", "jobs.backToJobs": "Volver a servicios",
    "jobs.filters": "Filtros de servicios", "jobs.quickFilters": "Filtros rápidos", "jobs.advancedFilters": "Filtros", "jobs.advancedFiltersCount": "Filtros ({count})", "jobs.quickToday": "Hoy", "jobs.search": "Buscar", "jobs.searchPlaceholder": "Buscar propiedad o dirección", "jobs.statusFilter": "Estado", "jobs.dateFilter": "Fecha", "jobs.cleanerFilter": "Cleaner", "jobs.propertyFilter": "Propiedad", "jobs.filterAll": "Todos", "jobs.filterOffered": "Ofrecidos", "jobs.filterAssigned": "Asignados", "jobs.filterCompleted": "Completados", "jobs.dateAny": "Cualquier fecha", "jobs.dateToday": "Hoy", "jobs.dateNext7Days": "Próximos 7 días", "jobs.datePast7Days": "Últimos 7 días", "jobs.datePast30Days": "Últimos 30 días", "jobs.anyCleaner": "Cualquier cleaner", "jobs.anyProperty": "Cualquier propiedad", "jobs.clearFilters": "Limpiar filtros", "jobs.results": "{count} servicios", "jobs.noMatchingFilters": "Ningún servicio coincide con estos filtros.",
    "jobs.loadMore": "Cargar más", "jobs.loadingMore": "Cargando más…",
    "payouts.title": "Pagos de cleaners", "payouts.refresh": "Actualizar", "payouts.loading": "Cargando pagos…", "payouts.error": "No se pudieron cargar los pagos.", "payouts.empty": "No hay pagos de cleaners pendientes.", "payouts.unpaidJobs": "Servicios sin pagar: {count}", "payouts.total": "Total adeudado", "payouts.review": "Revisar", "payouts.backToPayouts": "Volver a pagos", "payouts.paymentMethod": "Método de pago", "payouts.selectPaymentMethod": "Selecciona un método de pago", "payouts.note": "Nota (opcional)", "payouts.markPaid": "Marcar como pagado", "payouts.recording": "Registrando…", "payouts.jobsRequired": "Selecciona al menos un servicio.", "payouts.paymentMethodRequired": "Selecciona un método de pago.", "payouts.jobNoLongerPayable": "Uno o más servicios ya no están disponibles para pago. Actualiza y revisa nuevamente.", "payouts.recordError": "No se pudo registrar este pago.", "payouts.recorded": "Pago de {amount} registrado para {count} servicios.",
    "payouts.proof": "Comprobante de pago (opcional)", "payouts.proofHelper": "Usa una confirmación de pago recortada cuando sea posible. No incluyas saldos ni transacciones no relacionadas.", "payouts.proofSelected": "Seleccionado: {fileName}", "payouts.proofAttached": "Comprobante adjunto", "payouts.takePhoto": "Tomar foto", "payouts.chooseImage": "Elegir imagen", "payouts.attachProof": "Adjuntar comprobante", "payouts.retryProof": "Reintentar subir el comprobante", "payouts.viewProof": "Ver comprobante", "payouts.uploadingProof": "Subiendo comprobante… {percent}%", "payouts.proofRequired": "Elige una imagen de comprobante para reintentar.", "payouts.proofInvalidType": "Elige una imagen JPEG, PNG, WebP, HEIC o HEIF.", "payouts.proofTooLarge": "Elige una imagen de un máximo de 10 MB.", "payouts.proofUploadError": "No se pudo subir el comprobante.", "payouts.proofViewError": "No se pudo abrir el comprobante.", "payouts.proofRetryMessage": "El pago se registró, pero el comprobante no se subió. Puedes reintentar ahora o adjuntarlo después desde el historial de pagos.", "payouts.recentHistory": "Pagos recientes", "payouts.historyJobs": "Servicios: {count}",
    "offers.title": "Ofertas", "offers.offerToCleaners": "Ofrecer a cleaners", "offers.loadingCleaners": "Cargando cleaners…", "offers.cleanerError": "No se pudieron cargar las cleaners.", "offers.emptyCleaners": "No se encontraron cleaners activas.", "offers.send": "Enviar ofertas", "offers.sending": "Enviando ofertas…", "offers.sendError": "No se pudieron enviar las ofertas.", "offers.sent": "Ofertas enviadas", "offers.receivedOne": "{count} cleaner recibió una oferta.", "offers.receivedMany": "{count} cleaners recibieron ofertas.", "offers.loading": "Cargando ofertas…", "offers.error": "No se pudieron cargar las ofertas.", "offers.empty": "Aún no se enviaron ofertas.", "offers.refresh": "Actualizar ofertas", "offers.responded": "Respondió", "offers.simulateOffer": "Simular oferta", "offers.createPublicLink": "Crear enlace público", "offers.creatingPublicLink": "Creando enlace…", "offers.openPublicLink": "Abrir oferta pública para cleaner", "offers.publicLinkError": "No se pudo crear el enlace público de la oferta.", "offers.assign": "Asignar", "offers.assigning": "Asignando…", "offers.assignmentError": "No se pudo asignar la cleaner.", "offers.alreadyAssigned": "Este servicio ya está asignado.", "offers.simulateAssignedCleaner": "Simular cleaner responsable",
    "issues.title": "Problemas", "issues.loading": "Cargando problemas…", "issues.error": "No se pudieron cargar los problemas.", "issues.empty": "No se reportaron problemas.", "issues.refresh": "Actualizar problemas", "issues.reportedBy": "Reportado por {cleaner}", "issues.reported": "Reportado", "issues.resolved": "Resuelto", "issues.resolution": "Resolución", "issues.resolutionNote": "Nota de resolución (opcional)", "issues.resolve": "Resolver problema", "issues.resolving": "Resolviendo…", "issues.resolveError": "No se pudo resolver el problema.", "issues.alreadyResolved": "Este problema ya está resuelto.",
    "cleaner.developmentSimulation": "Simulación de desarrollo", "cleaner.offerTitle": "Oferta de limpieza", "cleaner.assignedTitle": "Limpieza asignada", "cleaner.inProgressTitle": "Limpieza en curso", "cleaner.completedTitle": "Limpieza completada", "cleaner.offerStatus": "Estado de la oferta", "cleaner.interested": "Me interesa", "cleaner.notAvailable": "No puedo", "cleaner.responseError": "No se pudo guardar tu respuesta.", "cleaner.start": "Iniciar limpieza", "cleaner.starting": "Iniciando…", "cleaner.startError": "No se pudo iniciar la limpieza.", "cleaner.reportIssue": "Informar un problema", "cleaner.complete": "Completar limpieza", "cleaner.completeConfirmation": "¿Completar esta limpieza?", "cleaner.completing": "Completando…", "cleaner.completeError": "No se pudo completar la limpieza.", "cleaner.issueTitle": "Problema de limpieza", "cleaner.issueCategory": "Categoría", "cleaner.issueDescription": "Descripción", "cleaner.reportedBy": "Reportado por", "cleaner.submitIssue": "Enviar problema", "cleaner.reporting": "Enviando…", "cleaner.issueError": "No se pudo informar el problema.", "cleaner.issueReported": "Problema informado", "cleaner.backToCleaning": "Volver a la limpieza",
    "publicOffer.eyebrow": "Oferta para cleaner", "publicOffer.title": "Oportunidad de limpieza", "publicOffer.loading": "Cargando oferta…", "publicOffer.notFound": "Este enlace de oferta no está disponible.", "publicOffer.expired": "Este enlace de oferta venció.", "publicOffer.unavailable": "Esta oferta ya no está disponible.", "publicOffer.loadError": "No se pudo cargar esta oferta.", "publicOffer.serviceDate": "Fecha del servicio", "publicOffer.startTime": "Hora de inicio", "publicOffer.yourPayment": "Tu pago", "publicOffer.status": "Estado de la oferta", "publicOffer.responding": "Guardando…", "publicOffer.responseError": "No se pudo guardar tu respuesta.", "publicOffer.interestedConfirmation": "Expresaste interés. La gerente confirmará la asignación.", "publicOffer.declinedConfirmation": "Avisaste a la gerente que no estás disponible.",
    "cleaners.title": "Cleaners", "cleaners.new": "Nueva cleaner", "cleaners.loading": "Cargando cleaners…", "cleaners.error": "No se pudieron cargar las cleaners.", "cleaners.empty": "No se encontraron cleaners.", "cleaners.edit": "Editar {cleaner}", "cleaners.view": "Ver {cleaner}", "cleaners.details": "Detalles de la cleaner", "cleaners.upcomingServices": "Próximos servicios", "cleaners.recentHistory": "Historial reciente", "cleaners.historyLoading": "Cargando historial de la cleaner…", "cleaners.historyError": "No se pudo cargar el historial de la cleaner.", "cleaners.noUpcomingServices": "No hay próximos servicios.", "cleaners.noRecentHistory": "No hay historial reciente de servicios.", "cleaners.noPhone": "Teléfono no informado", "cleaners.createTitle": "Nueva cleaner", "cleaners.editTitle": "Editar cleaner", "cleaners.name": "Nombre", "cleaners.phone": "Teléfono", "cleaners.phoneExample": "Ej.: +1 949 555 1234", "cleaners.preferredLanguage": "Idioma preferido", "cleaners.operations": "Operaciones", "cleaners.cityOrRegion": "Ciudad / región", "cleaners.teamType": "Tipo de equipo", "cleaners.teamTypeSolo": "Individual", "cleaners.teamTypeCouple": "Pareja", "cleaners.teamTypeTeam": "Equipo", "cleaners.teamTypeInvalid": "Elige un tipo de equipo válido.", "cleaners.payment": "Pago", "cleaners.preferredPaymentMethod": "Método de pago preferido", "cleaners.paymentContact": "Contacto de pago", "cleaners.paymentMethodCash": "Efectivo", "cleaners.paymentMethodCheck": "Cheque", "cleaners.paymentMethodOther": "Otro", "cleaners.preferredPaymentMethodInvalid": "Elige un método de pago válido.", "cleaners.internalNotes": "Notas internas", "cleaners.cityOrRegionTooLong": "Usa como máximo {count} caracteres para ciudad o región.", "cleaners.internalNotesTooLong": "Usa como máximo {count} caracteres en las notas internas.", "cleaners.paymentContactTooLong": "Usa como máximo {count} caracteres en el contacto de pago.", "cleaners.save": "Guardar", "cleaners.saving": "Guardando…", "cleaners.nameRequired": "Ingresa el nombre de la cleaner.", "cleaners.phoneRequired": "Ingresa un teléfono antes de guardar.", "cleaners.phoneInvalid": "Usa un teléfono internacional que comience con +.", "cleaners.preferredLanguageRequired": "Elige un idioma preferido.", "cleaners.createError": "No se pudo crear la cleaner.", "cleaners.updateError": "No se pudo actualizar la cleaner.", "cleaners.created": "Cleaner creada", "cleaners.updated": "Cleaner actualizada", "cleaners.backToDirectory": "Volver a cleaners", "cleaners.backToDetail": "Volver a la cleaner",
    "clients.title": "Clientes", "clients.new": "Nuevo cliente", "clients.loading": "Cargando clientes…", "clients.error": "No se pudieron cargar los clientes.", "clients.empty": "No se encontraron clientes.", "clients.createTitle": "Nuevo cliente", "clients.name": "Nombre del cliente", "clients.save": "Guardar cliente", "clients.creating": "Guardando…", "clients.nameRequired": "Ingresa un nombre de cliente.", "clients.createError": "No se pudo crear el cliente.", "clients.view": "Ver {client}", "clients.details": "Detalles del cliente", "clients.linkedProperties": "Propiedades vinculadas", "clients.propertiesLoading": "Cargando propiedades vinculadas…", "clients.propertiesError": "No se pudieron cargar las propiedades vinculadas.", "clients.noLinkedProperties": "No hay propiedades vinculadas.", "clients.openProperty": "Abrir propiedad", "clients.upcomingService": "Próximo servicio", "clients.noUpcomingService": "No hay próximo servicio", "clients.recentHistory": "Historial reciente", "clients.historyLoading": "Cargando historial del cliente…", "clients.historyError": "No se pudo cargar el historial del cliente.", "clients.noRecentHistory": "No hay historial reciente de servicios.",
    "dashboard.needsAttentionDescription": "Principales prioridades operativas entre asignaciones, interés de cleaners y problemas.",
  },
};

function getInitialLanguage() {
  if (typeof window === "undefined") return "en";

  const savedLanguage = window.localStorage.getItem(languageStorageKey);
  return messages[savedLanguage] ? savedLanguage : "en";
}

export function TranslationProvider({ children }) {
  const [language, setLanguage] = useState(getInitialLanguage);

  useEffect(() => {
    window.localStorage.setItem(languageStorageKey, language);
  }, [language]);

  const value = useMemo(() => {
    function translate(key, replacements = {}) {
      const message = messages[language][key] || messages.en[key] || key;
      return Object.entries(replacements).reduce(
        (result, [replacementKey, replacementValue]) => result.replaceAll(`{${replacementKey}}`, String(replacementValue)),
        message,
      );
    }

    return { language, setLanguage, translate };
  }, [language]);

  return createElement(TranslationContext.Provider, { value }, children);
}

export function useTranslation() {
  const translation = useContext(TranslationContext);
  if (!translation) throw new Error("useTranslation must be used within TranslationProvider");
  return translation;
}
