const organizationId = "cleanflow-demo";

export const demoScenarios = {
  quick: { jobCount: 10, label: "Quick Demo" },
  busyWeek: { jobCount: 35, label: "Busy Week" },
  payoutTest: { jobCount: 5, label: "Payout Test" },
};

function localDateKey(date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");

  return `${year}-${month}-${day}`;
}

function dateFromOffset(now, offset) {
  const date = new Date(now);
  date.setHours(12, 0, 0, 0);
  date.setDate(date.getDate() + offset);
  return localDateKey(date);
}

function demoFields({ batch, scenario, createdAt }) {
  return {
    demoSeed: true,
    demoSeedBatch: batch,
    demoSeedScenario: scenario,
    createdAt,
  };
}

export function isDemoSeedRecord(record) {
  return record?.data?.demoSeed === true;
}

export function selectDemoCleanupTargets(records) {
  return records.filter(isDemoSeedRecord);
}

export function buildDemoScenario({ scenario, batch, createdAt, now = new Date() }) {
  if (!demoScenarios[scenario]) {
    throw new Error("Unsupported demo scenario.");
  }

  const marker = demoFields({ batch, scenario, createdAt });
  const clientId = `${batch}-client`;
  const properties = [
    { id: `${batch}-property-coast`, name: "Demo Coast House" },
    { id: `${batch}-property-harbor`, name: "Demo Harbor Condo" },
    { id: `${batch}-property-garden`, name: "Demo Garden Suite" },
  ];
  const cleaners = [
    { id: `${batch}-cleaner-ava`, name: "Demo Cleaner Ava" },
    { id: `${batch}-cleaner-sam`, name: "Demo Cleaner Sam" },
    { id: `${batch}-cleaner-riley`, name: "Demo Cleaner Riley" },
  ];
  const client = {
    id: clientId,
    data: {
      organizationId,
      name: "Demo Operations Client",
      active: true,
      updatedAt: createdAt,
      ...marker,
    },
  };
  const propertyRecords = properties.map((property) => ({
    id: property.id,
    data: {
      organizationId,
      clientId,
      clientName: client.data.name,
      name: property.name,
      defaultClientPrice: 240,
      defaultCleanerPrice: 150,
      active: true,
      updatedAt: createdAt,
      ...marker,
    },
  }));
  const cleanerRecords = cleaners.map((cleaner) => ({
    id: cleaner.id,
    data: {
      organizationId,
      name: cleaner.name,
      active: true,
      preferredLanguage: "en",
      updatedAt: createdAt,
      ...marker,
    },
  }));
  const statuses = scenario === "payoutTest"
    ? ["COMPLETED"]
    : ["UNASSIGNED", "OFFERED", "ASSIGNED", "IN_PROGRESS", "COMPLETED"];
  const jobCount = demoScenarios[scenario].jobCount;
  const jobs = Array.from({ length: jobCount }, (_, index) => {
    const status = statuses[index % statuses.length];
    const property = properties[index % properties.length];
    const cleaner = cleaners[index % cleaners.length];
    const offset = scenario === "quick" ? index % 2 : scenario === "busyWeek" ? index % 7 : -index;
    const job = {
      id: `${batch}-job-${String(index + 1).padStart(2, "0")}`,
      data: {
        organizationId,
        clientId,
        clientName: client.data.name,
        propertyId: property.id,
        propertyName: property.name,
        scheduledDate: dateFromOffset(now, offset),
        scheduledStart: ["09:00", "11:00", "14:00"][index % 3],
        clientPrice: 240,
        cleanerPayout: 150,
        notes: "Demo data generated by CleanFlow Dev Center.",
        operationalStatus: status,
        ...marker,
      },
    };

    if (status !== "UNASSIGNED" && status !== "OFFERED") {
      job.data.assignedCleanerId = cleaner.id;
      job.data.assignedCleanerName = cleaner.name;
      job.data.assignedAt = createdAt;
    }
    if (status === "OFFERED") {
      job.data.offeredAt = createdAt;
    }
    if (status === "IN_PROGRESS" || status === "COMPLETED") {
      job.data.startedAt = createdAt;
    }
    if (status === "COMPLETED") {
      job.data.completedAt = createdAt;
    }

    return job;
  });
  const offers = jobs
    .filter((job) => job.data.operationalStatus === "OFFERED")
    .flatMap((job, index) => cleaners.slice(0, 2).map((cleaner, cleanerIndex) => ({
      jobId: job.id,
      id: cleaner.id,
      data: {
        jobId: job.id,
        cleanerId: cleaner.id,
        cleanerName: cleaner.name,
        status: cleanerIndex === 0 && index % 2 === 0 ? "INTERESTED" : "PENDING",
        ...marker,
      },
    })));

  return {
    client,
    properties: propertyRecords,
    cleaners: cleanerRecords,
    jobs,
    offers,
  };
}
