const organizationId = "cleanflow-demo";
// Dev Center scenarios intentionally remain singular-cleaner fixtures so v2 roster
// behavior is exercised explicitly rather than hidden behind generated legacy data.
const currentJobSchemaVersion = 1;

export const demoScenarios = {
  quick: { jobCount: 10, label: "Quick Demo" },
  busyWeek: { jobCount: 35, label: "Busy Week" },
  payoutTest: { jobCount: 5, label: "Payout Test" },
  managerTraining: { jobCount: 36, label: "Manager Training" },
  weeklyClose: { jobCount: 12, label: "Weekly Close" },
};

function localDateKey(date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");

  return `${year}-${month}-${day}`;
}

function dateFromOffset(now, offset) {
  const date = new Date(now);
  date.setHours(12, 0, 0, 0);
  date.setDate(date.getDate() + offset);
  return localDateKey(date);
}

function demoFields({ batch, scenario, createdAt }) {
  return {
    dataProvenance: "DEMO",
    demoSeed: true,
    demoSeedBatch: batch,
    demoSeedScenario: scenario,
    createdAt,
  };
}

export function isDemoSeedRecord(record) {
  return record?.data?.demoSeed === true;
}

export function selectDemoCleanupTargets(records) {
  return records.filter(isDemoSeedRecord);
}

function buildManagerTrainingScenario({ batch, createdAt, now }) {
  const scenario = "manager-training";
  const marker = demoFields({ batch, scenario, createdAt });
  const clients = [
    { id: `${batch}-client-harbor`, name: "Harbor Stay Co." },
    { id: `${batch}-client-sunset`, name: "Sunset Hosting" },
    { id: `${batch}-client-coastal`, name: "Coastal Key Management" },
  ].map((client) => ({
    ...client,
    data: {
      organizationId,
      name: client.name,
      active: true,
      updatedAt: createdAt,
      ...marker,
    },
  }));
  const properties = [
    ["seaside-loft", "Seaside Loft", 0],
    ["canyon-view-house", "Canyon View House", 1],
    ["harbor-studio", "Harbor Studio", 0],
    ["palm-court-condo", "Palm Court Condo", 2],
    ["maple-avenue-home", "Maple Avenue Home", 1],
    ["ocean-breeze-suite", "Ocean Breeze Suite", 0],
    ["ridge-retreat", "Ridge Retreat", 2],
    ["sunset-terrace", "Sunset Terrace", 1],
    ["garden-district-flat", "Garden District Flat", 2],
  ].map(([slug, name, clientIndex], index) => {
    const client = clients[clientIndex];
    return {
      id: `${batch}-property-${slug}`,
      name,
      clientId: client.id,
      data: {
        organizationId,
        clientId: client.id,
        clientName: client.name,
        name,
        defaultClientPrice: 220 + (index % 3) * 30,
        defaultCleanerPrice: 140 + (index % 3) * 20,
        active: true,
        updatedAt: createdAt,
        ...marker,
      },
    };
  });
  const cleaners = ["Ana", "Beatriz", "Camila", "Diana", "Elena", "Marina"].map((name) => ({
    id: `${batch}-cleaner-${name.toLowerCase()}`,
    name,
    data: {
      organizationId,
      name,
      active: true,
      preferredLanguage: "pt",
      updatedAt: createdAt,
      ...marker,
    },
  }));
  const statusPlan = [
    ...Array(8).fill("UNASSIGNED"),
    ...Array(7).fill("OFFERED"),
    ...Array(8).fill("ASSIGNED"),
    ...Array(3).fill("IN_PROGRESS"),
    ...Array(10).fill("COMPLETED"),
  ];
  const scheduledTimes = ["08:30", "10:30", "12:30", "14:30", "16:30", "18:00"];
  const jobs = statusPlan.map((status, index) => {
    const property = properties[(index * 2 + Math.floor(index / 7)) % properties.length];
    const cleaner = cleaners[index % cleaners.length];
    const client = clients.find((item) => item.id === property.clientId);
    const completedIndex = index - 26;
    const dayOffset = status === "COMPLETED" ? -3 + (completedIndex % 4) : index % 7;
    const job = {
      id: `${batch}-job-${String(index + 1).padStart(2, "0")}`,
      data: {
        organizationId,
        clientId: client.id,
        clientName: client.name,
        propertyId: property.id,
        propertyName: property.name,
        scheduledDate: dateFromOffset(now, dayOffset),
        scheduledStart: scheduledTimes[Math.floor(index / 7)],
        clientPrice: property.data.defaultClientPrice,
        cleanerPayout: property.data.defaultCleanerPrice,
        notes: "Manager training data generated by CleanFlow Dev Center.",
        operationalStatus: status,
        schemaVersion: currentJobSchemaVersion,
        ...marker,
      },
    };

    if (!["UNASSIGNED", "OFFERED"].includes(status)) {
      job.data.assignedCleanerId = cleaner.id;
      job.data.assignedCleanerName = cleaner.name;
      job.data.assignedAt = createdAt;
    }
    if (status === "OFFERED") job.data.offeredAt = createdAt;
    if (["IN_PROGRESS", "COMPLETED"].includes(status)) job.data.startedAt = createdAt;
    if (status === "COMPLETED") job.data.completedAt = createdAt;

    return job;
  });
  const offeredJobs = jobs.filter((job) => job.data.operationalStatus === "OFFERED");
  const offers = offeredJobs.flatMap((job, jobIndex) => cleaners.slice(0, 2).map((cleaner, cleanerIndex) => ({
    jobId: job.id,
    id: cleaner.id,
    data: {
      jobId: job.id,
      cleanerId: cleaner.id,
      cleanerName: cleaner.name,
      status: cleanerIndex === 0 && jobIndex < 3
        ? "INTERESTED"
        : cleanerIndex === 1 && jobIndex < 2
          ? "DECLINED"
          : "PENDING",
      ...marker,
    },
  })));
  const issueJobs = [jobs[23], jobs[24], jobs[31]];
  const issues = [
    ["ACCESS", "Keypad is not responding at arrival.", "OPEN"],
    ["SUPPLIES", "Paper towels are running low.", "OPEN"],
    ["BROKEN_ITEM", "Coffee maker is not working.", "RESOLVED"],
  ].map(([category, description, status], index) => {
    const job = issueJobs[index];
    const cleaner = cleaners[(index + 1) % cleaners.length];
    return {
      jobId: job.id,
      id: `${batch}-issue-${index + 1}`,
      data: {
        jobId: job.id,
        propertyId: job.data.propertyId,
        cleanerId: cleaner.id,
        cleanerName: cleaner.name,
        category,
        description,
        status,
        ...(status === "RESOLVED" ? { resolvedAt: createdAt, resolutionNote: "Manager reviewed the training issue." } : {}),
        ...marker,
      },
    };
  });

  return { client: clients[0], clients, properties, cleaners, jobs, offers, issues };
}

function buildWeeklyCloseScenario({ batch, createdAt, now }) {
  const marker = demoFields({ batch, scenario: "weeklyClose", createdAt });
  // Match the Weekly Close view's date-only America/Los_Angeles service week.
  const parts = new Intl.DateTimeFormat("en-US", {
    timeZone: "America/Los_Angeles", year: "numeric", month: "2-digit", day: "2-digit",
  }).formatToParts(now);
  const value = (type) => parts.find((part) => part.type === type).value;
  const monday = new Date(`${value("year")}-${value("month")}-${value("day")}T12:00:00Z`);
  monday.setUTCDate(monday.getUTCDate() - (monday.getUTCDay() + 6) % 7 - 7);
  const serviceDate = (offset) => {
    const date = new Date(monday);
    date.setUTCDate(date.getUTCDate() + offset);
    return date.toISOString().slice(0, 10);
  };
  const clients = ["Alpha", "Beta", "Gamma"].map((name) => ({
    id: `${batch}-client-${name.toLowerCase()}`,
    data: { organizationId, name: `Weekly Demo Client ${name}`, active: true, updatedAt: createdAt, ...marker },
  }));
  const cleaner = {
    id: `${batch}-cleaner`,
    data: { organizationId, name: "Weekly Demo Cleaner", active: true, preferredLanguage: "en", updatedAt: createdAt, ...marker },
  };
  const rows = [
    ["paid", 0, 200, 100, 0],
    ["outstanding", 0, 180, 80, 1],
    ["v2", 1, 240, 120, 2],
    ["batch-a", 1, 140, 70, 3],
    ["batch-b", 1, 90, 40, 4],
    ["missing-charge", 2, null, 90, 5],
    ["missing-payout", 2, 110, null, 6],
    ["zero", 2, 0, 0, 6],
    ["archived", 0, 900, 400, 3],
    ["unfinished", 0, 800, 350, 3],
    ["unknown-provenance", 0, 700, 300, 3],
    ["outside-week", 1, 100, 50, 7],
  ];
  const properties = rows.map(([key, clientIndex]) => ({
    id: `${batch}-property-${key}`,
    data: { organizationId, name: `Weekly Demo ${key}`, clientId: clients[clientIndex].id, clientName: clients[clientIndex].data.name, active: true, updatedAt: createdAt, ...marker },
  }));
  const jobs = rows.map(([key, clientIndex, clientPrice, cleanerPayout, offset], index) => {
    const property = properties[index];
    const data = {
      organizationId, clientId: clients[clientIndex].id, clientName: clients[clientIndex].data.name,
      propertyId: property.id, propertyName: property.data.name,
      scheduledDate: serviceDate(offset), scheduledStart: "11:00", operationalStatus: "COMPLETED",
      completedAt: createdAt, assignedCleanerId: cleaner.id, assignedCleanerName: cleaner.data.name,
      schemaVersion: 1, legacyPayoutEligible: true,
      ...(clientPrice === null ? {} : { clientPrice }),
      ...(cleanerPayout === null ? {} : { cleanerPayout }),
      ...marker,
      // REAL is solely a synthetic eligibility fixture; demoSeed remains the reset authority.
      dataProvenance: "REAL",
    };
    if (key === "paid") {
      data.payoutId = `${batch}-payout-paid`;
      data.payoutPaidAt = createdAt;
    }
    if (key.startsWith("batch-")) {
      data.payoutId = `${batch}-payout-batch`;
      data.payoutPaidAt = createdAt;
    }
    if (key === "v2") {
      data.schemaVersion = 2;
      data.assignedCleanerIds = [cleaner.id];
      delete data.assignedCleanerId;
      delete data.assignedCleanerName;
      delete data.legacyPayoutEligible;
    }
    if (key === "archived") data.archivedAt = createdAt;
    if (key === "unfinished") data.operationalStatus = "ASSIGNED";
    if (key === "unknown-provenance") data.dataProvenance = "UNKNOWN";
    return { id: `${batch}-job-${key}`, data };
  });
  const payouts = [
    { id: `${batch}-payout-paid`, amount: 100, jobIds: [`${batch}-job-paid`] },
    { id: `${batch}-payout-batch`, amount: 110, jobIds: [`${batch}-job-batch-a`, `${batch}-job-batch-b`] },
  ].map(({ id, ...payment }) => ({
    id, data: { organizationId, cleanerId: cleaner.id, cleanerNameSnapshot: cleaner.data.name, status: "PAID", paymentMethod: "CASH", paidAt: createdAt, ...payment, ...marker },
  }));
  return { client: clients[0], clients, properties, cleaners: [cleaner], jobs, payouts, offers: [], issues: [] };
}

export function buildDemoScenario({ scenario, batch, createdAt, now = new Date() }) {
  if (!demoScenarios[scenario]) {
    throw new Error("Unsupported demo scenario.");
  }

  if (scenario === "managerTraining") {
    return buildManagerTrainingScenario({ batch, createdAt, now });
  }

  if (scenario === "weeklyClose") {
    return buildWeeklyCloseScenario({ batch, createdAt, now });
  }

  const marker = demoFields({ batch, scenario, createdAt });
  const clientId = `${batch}-client`;
  const properties = [
    { id: `${batch}-property-coast`, name: "Demo Coast House" },
    { id: `${batch}-property-harbor`, name: "Demo Harbor Condo" },
    { id: `${batch}-property-garden`, name: "Demo Garden Suite" },
  ];
  const cleaners = [
    { id: `${batch}-cleaner-ava`, name: "Demo Cleaner Ava" },
    { id: `${batch}-cleaner-sam`, name: "Demo Cleaner Sam" },
    { id: `${batch}-cleaner-riley`, name: "Demo Cleaner Riley" },
  ];
  const client = {
    id: clientId,
    data: {
      organizationId,
      name: "Demo Operations Client",
      active: true,
      updatedAt: createdAt,
      ...marker,
    },
  };
  const propertyRecords = properties.map((property) => ({
    id: property.id,
    data: {
      organizationId,
      clientId,
      clientName: client.data.name,
      name: property.name,
      defaultClientPrice: 240,
      defaultCleanerPrice: 150,
      active: true,
      updatedAt: createdAt,
      ...marker,
    },
  }));
  const cleanerRecords = cleaners.map((cleaner) => ({
    id: cleaner.id,
    data: {
      organizationId,
      name: cleaner.name,
      active: true,
      preferredLanguage: "en",
      updatedAt: createdAt,
      ...marker,
    },
  }));
  const statuses = scenario === "payoutTest"
    ? ["COMPLETED"]
    : ["UNASSIGNED", "OFFERED", "ASSIGNED", "IN_PROGRESS", "COMPLETED"];
  const jobCount = demoScenarios[scenario].jobCount;
  const jobs = Array.from({ length: jobCount }, (_, index) => {
    const status = statuses[index % statuses.length];
    const property = properties[index % properties.length];
    const cleaner = cleaners[index % cleaners.length];
    const offset = scenario === "quick" ? index % 2 : scenario === "busyWeek" ? index % 7 : -index;
    const job = {
      id: `${batch}-job-${String(index + 1).padStart(2, "0")}`,
      data: {
        organizationId,
        clientId,
        clientName: client.data.name,
        propertyId: property.id,
        propertyName: property.name,
        scheduledDate: dateFromOffset(now, offset),
        scheduledStart: ["09:00", "11:00", "14:00"][index % 3],
        clientPrice: 240,
        cleanerPayout: 150,
        notes: "Demo data generated by CleanFlow Dev Center.",
        operationalStatus: status,
        schemaVersion: currentJobSchemaVersion,
        ...marker,
      },
    };

    if (status !== "UNASSIGNED" && status !== "OFFERED") {
      job.data.assignedCleanerId = cleaner.id;
      job.data.assignedCleanerName = cleaner.name;
      job.data.assignedAt = createdAt;
    }
    if (status === "OFFERED") {
      job.data.offeredAt = createdAt;
    }
    if (status === "IN_PROGRESS" || status === "COMPLETED") {
      job.data.startedAt = createdAt;
    }
    if (status === "COMPLETED") {
      job.data.completedAt = createdAt;
    }

    return job;
  });
  const offers = jobs
    .filter((job) => job.data.operationalStatus === "OFFERED")
    .flatMap((job, index) => cleaners.slice(0, 2).map((cleaner, cleanerIndex) => ({
      jobId: job.id,
      id: cleaner.id,
      data: {
        jobId: job.id,
        cleanerId: cleaner.id,
        cleanerName: cleaner.name,
        status: cleanerIndex === 0 && index % 2 === 0 ? "INTERESTED" : "PENDING",
        ...marker,
      },
    })));

  return {
    client,
    clients: [client],
    properties: propertyRecords,
    cleaners: cleanerRecords,
    jobs,
    offers,
    issues: [],
  };
}
