const organizationId = "cleanflow-demo";
const currentJobSchemaVersion = 1;

export const demoScenarios = {
  quick: { jobCount: 10, label: "Quick Demo" },
  busyWeek: { jobCount: 35, label: "Busy Week" },
  payoutTest: { jobCount: 5, label: "Payout Test" },
  managerTraining: { jobCount: 36, label: "Manager Training" },
};

function localDateKey(date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");

  return `${year}-${month}-${day}`;
}

function dateFromOffset(now, offset) {
  const date = new Date(now);
  date.setHours(12, 0, 0, 0);
  date.setDate(date.getDate() + offset);
  return localDateKey(date);
}

function demoFields({ batch, scenario, createdAt }) {
  return {
    demoSeed: true,
    demoSeedBatch: batch,
    demoSeedScenario: scenario,
    createdAt,
  };
}

export function isDemoSeedRecord(record) {
  return record?.data?.demoSeed === true;
}

export function selectDemoCleanupTargets(records) {
  return records.filter(isDemoSeedRecord);
}

function buildManagerTrainingScenario({ batch, createdAt, now }) {
  const scenario = "manager-training";
  const marker = demoFields({ batch, scenario, createdAt });
  const clients = [
    { id: `${batch}-client-harbor`, name: "Harbor Stay Co." },
    { id: `${batch}-client-sunset`, name: "Sunset Hosting" },
    { id: `${batch}-client-coastal`, name: "Coastal Key Management" },
  ].map((client) => ({
    ...client,
    data: {
      organizationId,
      name: client.name,
      active: true,
      updatedAt: createdAt,
      ...marker,
    },
  }));
  const properties = [
    ["seaside-loft", "Seaside Loft", 0],
    ["canyon-view-house", "Canyon View House", 1],
    ["harbor-studio", "Harbor Studio", 0],
    ["palm-court-condo", "Palm Court Condo", 2],
    ["maple-avenue-home", "Maple Avenue Home", 1],
    ["ocean-breeze-suite", "Ocean Breeze Suite", 0],
    ["ridge-retreat", "Ridge Retreat", 2],
    ["sunset-terrace", "Sunset Terrace", 1],
    ["garden-district-flat", "Garden District Flat", 2],
  ].map(([slug, name, clientIndex], index) => {
    const client = clients[clientIndex];
    return {
      id: `${batch}-property-${slug}`,
      name,
      clientId: client.id,
      data: {
        organizationId,
        clientId: client.id,
        clientName: client.name,
        name,
        defaultClientPrice: 220 + (index % 3) * 30,
        defaultCleanerPrice: 140 + (index % 3) * 20,
        active: true,
        updatedAt: createdAt,
        ...marker,
      },
    };
  });
  const cleaners = ["Ana", "Beatriz", "Camila", "Diana", "Elena", "Marina"].map((name) => ({
    id: `${batch}-cleaner-${name.toLowerCase()}`,
    name,
    data: {
      organizationId,
      name,
      active: true,
      preferredLanguage: "pt",
      updatedAt: createdAt,
      ...marker,
    },
  }));
  const statusPlan = [
    ...Array(8).fill("UNASSIGNED"),
    ...Array(7).fill("OFFERED"),
    ...Array(8).fill("ASSIGNED"),
    ...Array(3).fill("IN_PROGRESS"),
    ...Array(10).fill("COMPLETED"),
  ];
  const scheduledTimes = ["08:30", "10:30", "12:30", "14:30", "16:30", "18:00"];
  const jobs = statusPlan.map((status, index) => {
    const property = properties[(index * 2 + Math.floor(index / 7)) % properties.length];
    const cleaner = cleaners[index % cleaners.length];
    const client = clients.find((item) => item.id === property.clientId);
    const completedIndex = index - 26;
    const dayOffset = status === "COMPLETED" ? -3 + (completedIndex % 4) : index % 7;
    const job = {
      id: `${batch}-job-${String(index + 1).padStart(2, "0")}`,
      data: {
        organizationId,
        clientId: client.id,
        clientName: client.name,
        propertyId: property.id,
        propertyName: property.name,
        scheduledDate: dateFromOffset(now, dayOffset),
        scheduledStart: scheduledTimes[Math.floor(index / 7)],
        clientPrice: property.data.defaultClientPrice,
        cleanerPayout: property.data.defaultCleanerPrice,
        notes: "Manager training data generated by CleanFlow Dev Center.",
        operationalStatus: status,
        schemaVersion: currentJobSchemaVersion,
        ...marker,
      },
    };

    if (!["UNASSIGNED", "OFFERED"].includes(status)) {
      job.data.assignedCleanerId = cleaner.id;
      job.data.assignedCleanerName = cleaner.name;
      job.data.assignedAt = createdAt;
    }
    if (status === "OFFERED") job.data.offeredAt = createdAt;
    if (["IN_PROGRESS", "COMPLETED"].includes(status)) job.data.startedAt = createdAt;
    if (status === "COMPLETED") job.data.completedAt = createdAt;

    return job;
  });
  const offeredJobs = jobs.filter((job) => job.data.operationalStatus === "OFFERED");
  const offers = offeredJobs.flatMap((job, jobIndex) => cleaners.slice(0, 2).map((cleaner, cleanerIndex) => ({
    jobId: job.id,
    id: cleaner.id,
    data: {
      jobId: job.id,
      cleanerId: cleaner.id,
      cleanerName: cleaner.name,
      status: cleanerIndex === 0 && jobIndex < 3
        ? "INTERESTED"
        : cleanerIndex === 1 && jobIndex < 2
          ? "DECLINED"
          : "PENDING",
      ...marker,
    },
  })));
  const issueJobs = [jobs[23], jobs[24], jobs[31]];
  const issues = [
    ["ACCESS", "Keypad is not responding at arrival.", "OPEN"],
    ["SUPPLIES", "Paper towels are running low.", "OPEN"],
    ["BROKEN_ITEM", "Coffee maker is not working.", "RESOLVED"],
  ].map(([category, description, status], index) => {
    const job = issueJobs[index];
    const cleaner = cleaners[(index + 1) % cleaners.length];
    return {
      jobId: job.id,
      id: `${batch}-issue-${index + 1}`,
      data: {
        jobId: job.id,
        propertyId: job.data.propertyId,
        cleanerId: cleaner.id,
        cleanerName: cleaner.name,
        category,
        description,
        status,
        ...(status === "RESOLVED" ? { resolvedAt: createdAt, resolutionNote: "Manager reviewed the training issue." } : {}),
        ...marker,
      },
    };
  });

  return { client: clients[0], clients, properties, cleaners, jobs, offers, issues };
}

export function buildDemoScenario({ scenario, batch, createdAt, now = new Date() }) {
  if (!demoScenarios[scenario]) {
    throw new Error("Unsupported demo scenario.");
  }

  if (scenario === "managerTraining") {
    return buildManagerTrainingScenario({ batch, createdAt, now });
  }

  const marker = demoFields({ batch, scenario, createdAt });
  const clientId = `${batch}-client`;
  const properties = [
    { id: `${batch}-property-coast`, name: "Demo Coast House" },
    { id: `${batch}-property-harbor`, name: "Demo Harbor Condo" },
    { id: `${batch}-property-garden`, name: "Demo Garden Suite" },
  ];
  const cleaners = [
    { id: `${batch}-cleaner-ava`, name: "Demo Cleaner Ava" },
    { id: `${batch}-cleaner-sam`, name: "Demo Cleaner Sam" },
    { id: `${batch}-cleaner-riley`, name: "Demo Cleaner Riley" },
  ];
  const client = {
    id: clientId,
    data: {
      organizationId,
      name: "Demo Operations Client",
      active: true,
      updatedAt: createdAt,
      ...marker,
    },
  };
  const propertyRecords = properties.map((property) => ({
    id: property.id,
    data: {
      organizationId,
      clientId,
      clientName: client.data.name,
      name: property.name,
      defaultClientPrice: 240,
      defaultCleanerPrice: 150,
      active: true,
      updatedAt: createdAt,
      ...marker,
    },
  }));
  const cleanerRecords = cleaners.map((cleaner) => ({
    id: cleaner.id,
    data: {
      organizationId,
      name: cleaner.name,
      active: true,
      preferredLanguage: "en",
      updatedAt: createdAt,
      ...marker,
    },
  }));
  const statuses = scenario === "payoutTest"
    ? ["COMPLETED"]
    : ["UNASSIGNED", "OFFERED", "ASSIGNED", "IN_PROGRESS", "COMPLETED"];
  const jobCount = demoScenarios[scenario].jobCount;
  const jobs = Array.from({ length: jobCount }, (_, index) => {
    const status = statuses[index % statuses.length];
    const property = properties[index % properties.length];
    const cleaner = cleaners[index % cleaners.length];
    const offset = scenario === "quick" ? index % 2 : scenario === "busyWeek" ? index % 7 : -index;
    const job = {
      id: `${batch}-job-${String(index + 1).padStart(2, "0")}`,
      data: {
        organizationId,
        clientId,
        clientName: client.data.name,
        propertyId: property.id,
        propertyName: property.name,
        scheduledDate: dateFromOffset(now, offset),
        scheduledStart: ["09:00", "11:00", "14:00"][index % 3],
        clientPrice: 240,
        cleanerPayout: 150,
        notes: "Demo data generated by CleanFlow Dev Center.",
        operationalStatus: status,
        schemaVersion: currentJobSchemaVersion,
        ...marker,
      },
    };

    if (status !== "UNASSIGNED" && status !== "OFFERED") {
      job.data.assignedCleanerId = cleaner.id;
      job.data.assignedCleanerName = cleaner.name;
      job.data.assignedAt = createdAt;
    }
    if (status === "OFFERED") {
      job.data.offeredAt = createdAt;
    }
    if (status === "IN_PROGRESS" || status === "COMPLETED") {
      job.data.startedAt = createdAt;
    }
    if (status === "COMPLETED") {
      job.data.completedAt = createdAt;
    }

    return job;
  });
  const offers = jobs
    .filter((job) => job.data.operationalStatus === "OFFERED")
    .flatMap((job, index) => cleaners.slice(0, 2).map((cleaner, cleanerIndex) => ({
      jobId: job.id,
      id: cleaner.id,
      data: {
        jobId: job.id,
        cleanerId: cleaner.id,
        cleanerName: cleaner.name,
        status: cleanerIndex === 0 && index % 2 === 0 ? "INTERESTED" : "PENDING",
        ...marker,
      },
    })));

  return {
    client,
    clients: [client],
    properties: propertyRecords,
    cleaners: cleanerRecords,
    jobs,
    offers,
    issues: [],
  };
}
